---
language: python
python: "2.7"
os: linux
dist: trusty
env:
  - ansible_version="2.4.0.0"
  - ansible_version="2.4.1.0"
  - ansible_version="2.4.2.0"

sudo: required

# Install ansible

before_install:
  - sudo apt-get install python-setuptools
  - sudo easy_install pip
  # Install ansible
  - sudo pip install -I "ansible==$ansible_version"

install:
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # # Test Demo case 1
  # - ansible-playbook tests/test.yml -i tests/inventory -v
  # # test login pages
  # - curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
