---
- name: "[NGINX] -  Required and recommended packages are installed."
  package: "name={{ item }} state=present"
  with_items:
    - nginx
    - smbclient
    - "php{{ php_ver }}-fpm"
    - "php{{ php_ver }}-gd"
    - "php{{ php_ver }}-ldap"
    - "php{{ php_ver }}-imap"
    - "php{{ php_ver }}-json"
    - "php{{ php_ver }}-curl"
    - "php{{ php_ver }}-intl"
    - "php{{ php_ver }}-mcrypt"
  notify: [ "start nginx", "start php-fpm" ]

- name: "[NGINX] -  Some other pakages are installed."
  package: "name={{ item }} state=present"
  with_items: "{{ php_pkg_spe }}"

- name: "[NGINX] -  APCu is installed."
  package: "name={{ php_pkg_apcu }} state=present"
  when : ansible_distribution_release not in [ "trusty" ]

- block:
  # load APCu from backports as the default version for trusty is obsolete.
  - name: "[NGINX] -  Configure trusty backport."
    apt_repository:
      repo: "deb http://fr.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse"
      state: present
      update_cache: yes
  - name: "[NGINX] -  Install APCu from backports."
    apt: "name={{ php_pkg_apcu }} state=latest default_release=trusty-backports"
  when: ansible_distribution_release == "trusty"

- name: "[NGINX] -  remove some commented line in php-fpm conf"
  lineinfile:
    dest: "{{ php_dir }}/fpm/pool.d/www.conf"
    regexp: '^\;env'
    state: absent
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"
  notify: reload php-fpm

- name: "[NGINX] -  Add path variable to php-fpm"
  blockinfile:
    dest: "{{ php_dir }}/fpm/pool.d/www.conf"
    insertafter: '^; Default Value: clean env$'
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
    block: |
      env[HOSTNAME] = $HOSTNAME
      env[PATH] = $PATH
      env[TMP] = /tmp
      env[TMPDIR] = /tmp
      env[TEMP] = /tmp
  notify: reload php-fpm

- name: "[NGINX] -  enable APC for php CLI"
  lineinfile:
    dest: "{{ php_dir }}/cli/php.ini"
    line: "apc.enable_cli = 1"
    insertbefore: "^; End:$"
    state: present
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"
  notify: reload php-fpm

- name: "[NGINX] -  Public Diffie-Hellman Parameter are generated. This might take a while."
  command: "openssl dhparam -out {{ nextcloud_tls_dhparam }} 2048"
  args:
    creates: "{{ nextcloud_tls_dhparam }}"

- name: "[NGINX] -  php handler configuration is present."
  template:
    dest: /etc/nginx/sites-available/php_handler.cnf
    src: templates/nginx_php_handler.j2
  notify: reload nginx

- name: "[NGINX] -  php handler is enabled"
  file:
    path: /etc/nginx/sites-enabled/php_handler
    src: /etc/nginx/sites-available/php_handler.cnf
    state: link
  notify: reload nginx

- name: "[NGINX] -  generate Nextcloud configuration for nginx"
  template:
    dest: /etc/nginx/sites-available/nc_{{ nextcloud_instance_name }}.cnf
    src: templates/nginx_nc_root.j2
  notify: reload nginx

- name: "[NGINX] -  Enable Nextcloud in nginx conf"
  file:
    path: /etc/nginx/sites-enabled/nc_{{ nextcloud_instance_name }}
    src: /etc/nginx/sites-available/nc_{{ nextcloud_instance_name }}.cnf
    state: link
    # validate: "/usr/sbin/nginx -t #%s"
  notify: reload nginx
