---
# tasks file for nextcloud
- include: tasks/setup_env.yml
  # load os specific variables

- name: Verify permission for installed TLS certificates
  include: tasks/tls_installed.yml
  when: nextcloud_tls_cert_method == "installed"
  
- name: Instal given signed certificates
  include: tasks/tls_signed.yml
  when: nextcloud_tls_cert_method == "signed"

- name: configure self signed TLS certificates
  include: tasks/tls_selfsigned.yml
  when: nextcloud_tls_cert_method == "self-signed"

- name: Install certificates with letsencrypt
  include: tasks/tls_certbot.yml
  when: nextcloud_tls_cert_method == "certbot"

- name: Configure Nginx web server.
  include: tasks/http_nginx.yml
  when: nextcloud_websrv == "nginx"

- name: Configure Apache web server
  include: tasks/http_apache.yml
  when: nextcloud_websrv == "apache"

- name: Configure {{ nextcloud_db_backend }} database
  include: tasks/db_mysql.yml
  when: nextcloud_db_backend in ["mysql", "mariadb"] and nextcloud_install_db == true
  
- name: Configure PostgreSQL database
  include: tasks/db_postgresql.yml
  when: nextcloud_db_backend in ["pgsql"] and nextcloud_install_db == true
  
  # will not run occ installation if already installed => config.php exists : 
# - name: Check Nextcloud installation file 
  # stat: "path={{ nextcloud_webroot }}/config/config.php"
  # register: wroot
  
- name: Downloading Nextcloud 
  include: tasks/nc_download.yml

- name: Nextcloud installation
  include: tasks/nc_installation.yml
  # when: wroot.stat.exists is defined and not wroot.stat.exists
