---
# additionnal setup and fixes for OS dependent environment
- name: "controls nextcloud_trusted_domain type"
  fail:
    msg: "New versions require nextcloud_trusted_domain to be declared as a list."
  when: nextcloud_trusted_domain is string

- name: "[ENV] - ca-certificate are up to date"
  # needed for downloading from download.nextcloud.com as the site use letsencrypt certificates
  # letsencrypt may not be trusted on older OS
  apt: cache_valid_time=86400 update_cache=yes name=ca-certificates state=latest
  when: ansible_os_family in [ "Debian" ]

- name: "[ENV] - Load environment for OS using php 5"
  include_vars: "{{ role_path }}/defaults/php5_env.yml"
  when: ansible_distribution_release in [ "trusty", "jessie" ]

- name: "[ENV] - Load environment for OS using php 7.0"
  include_vars: "{{ role_path }}/defaults/php7.0_env.yml"
  when: ansible_distribution_release in [ "xenial" ]

  # fix for debian not using sudo :
  # defining if sudo is installed or not
- name: "[ENV] - Debian only : checking sudo."
  shell: "dpkg -l sudo"
  changed_when: False
  register: nc_sudo_installed_result
  failed_when: False
  when: ansible_distribution == "Debian"

- name: "[ENV] - rolling back to su."
  set_fact: ansible_become_method="su"
  when: nc_sudo_installed_result is defined and nc_sudo_installed_result.rc != 0

# fix for ubuntu 14.04 with permission issue for unprivileged user :
- name: "[NC] - Adding ACL on trusty."
  apt:
    name: acl
    state: installed
  when: ansible_distribution_release == "trusty"
