---
galaxy_info:
  author: aalaesar
  role_name: backup
  description: Create a backup of your nextcloud server with this ansible role

  license: BSD

  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - backup
    - nextcloud
    - storage
    - selfhosted
    - privacy

dependencies: []
