---
galaxy_info:
  author: aalaesar
  role_name: install_nextcloud
  description: Install Nextcloud server like you want ! Apache2 or Nginx ? MariaDB or PostgresQL ? You choose, you watch, it works !

  license: BSD

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

    - name: Debian
      versions:
        - bookworm
        - bullseye
  galaxy_tags:
    - nextcloud
    - filesharing
    - installation
    - private
    - cloud

dependencies: []
