---
# defaults file for nextcloud
# [DOWNLOAD]
# An URL will be generated following naming rules used by nextcloud's repository
# Not following this rules correctly will make the role unable to download nextcloud.
nextcloud_version_channel: "releases"  # mandatory # (releases/prereleases/daily)
# channel releases requires version_full.
# channel prereleases requires version_full. Optional: version_special.
# channel daily requires requires version_full & version_special.
nextcloud_get_latest: true  # mandatory # specify if the latest archive should be downloaded.
# Override generated file name for channels: releases/daily.
# optional : version_major.
# nextcloud_version_major: 25 # (24/25/26) for releases or for daily (master/stable25/stable26...)
# nextcloud_version_full: "25.0.3" # full version string
# nextcloud_version_special: "" #  For prereleases: "RCn/beta" or for daily "YYYY-MM-DD"
nextcloud_repository: "https://download.nextcloud.com/server"  # Domain URL where to download Nextcloud.
nextcloud_archive_format: "zip"  # zip/tar.bz2
# nextcloud_full_url: "https://download.nextcloud.com/server/releases/nextcloud-25.0.0.zip"  # specify directly a full URL to the archive


# [PHP CONFIG AND EXTENSIONS]
# PHP configs
# by default, use references stored in defaults/php_configs.yml
php_install_external_repos: true
php_ver: "8.1"
php_dir: "/etc/php/{{ php_ver }}"
php_bin: "php-fpm{{ php_ver }}"
php_pkg_spe:
  - "php{{ php_ver }}-bcmath"
  - "php{{ php_ver }}-gmp"
  - "php{{ php_ver }}-imagick"
  - "php{{ php_ver }}-mbstring"
  - "php{{ php_ver }}-xml"
  - "php{{ php_ver }}-zip"
php_socket: "/run/php/php{{ php_ver }}-fpm.sock"
php_memory_limit: 512M

# [NEXTCLOUD CONFIG]
nextcloud_trusted_domain:
  - "{{ ansible_fqdn }}"
  - "{{ ansible_default_ipv4.address }}"

nextcloud_ipv6: false

nextcloud_trusted_proxies: []

nextcloud_instance_name: "{{ nextcloud_trusted_domain | first }}"

nextcloud_install_websrv: true
nextcloud_websrv: "apache2"  # "apache2"/"nginx"
nextcloud_websrv_user: "{{ os_config_ref[ansible_os_family | lower].defaults.nextcloud_websrv_user }}"
nextcloud_websrv_group: "{{ os_config_ref[ansible_os_family | lower].defaults.nextcloud_websrv_group }}"
nextcloud_disable_websrv_default_site: false
nextcloud_websrv_template: "templates/{{ nextcloud_websrv }}_nc.j2"
nextcloud_webroot: "/opt/nextcloud"
nextcloud_data_dir: "/var/ncdata"
nextcloud_admin_name: "admin"
# nextcloud_admin_pwd: "secret"

nextcloud_install_redis_server: true
nextcloud_redis_host: '/var/run/redis/redis.sock'
nextcloud_redis_port: 0

nextcloud_redis_settings:
  - { name: 'redis host', value: '"{{ nextcloud_redis_host }}"' }
  - { name: 'redis port', value: "{{ nextcloud_redis_port }}" }
  - { name: 'memcache.locking', value: '\OC\Memcache\Redis' }

nextcloud_background_cron: true

## Custom nextcloud settings
## https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html
nextcloud_config_settings:
  - { name: 'default_phone_region', value: 'DE' }  # set a country code using ISO 3166-1
  - { name: 'overwrite.cli.url', value: 'https://{{ nextcloud_trusted_domain | first }}' }
  - { name: 'memcache.local', value: '\OC\Memcache\APCu' }
  - { name: 'mysql.utf8mb4', value: true }
  - { name: 'updater.release.channel', value: 'production' }  # production/stable/daily/beta

# [DATABASE]
nextcloud_install_db: true
nextcloud_db_host: "127.0.0.1"
nextcloud_db_backend: "mysql"  # mysql/mariadb/pgsql
mysql_daemon: >-
  {{
  os_config_ref[ansible_distribution | lower][ansible_distribution_release | lower].mysql_daemon |
  default(os_config_ref[ansible_distribution | lower].defaults.mysql_daemon)
  }}
nextcloud_db_enabled_on_startup: true
nextcloud_db_name: "nextcloud"
nextcloud_db_admin: "ncadmin"
# nextcloud_db_pwd: "secret"
# Set this to `true` to forcibly update the root password.
nextcloud_mysql_root_pwd_update: false

# [TLS] parameters used in the apache2 & nginx templates
##  max file's size allowed to be uploaded on the server
nextcloud_max_upload_size: 512m  # in Byte or human readable size notation (g/m/k)
nextcloud_install_tls: true
nextcloud_tls_enforce: true
nextcloud_mozilla_modern_ssl_profile: false  # when false, intermediate profile is used
nextcloud_tls_cert_method: "self-signed"  # self-signed/signed/installed
nextcloud_tls_dhparam: "/etc/ssl/dhparam.pem"
nextcloud_hsts: false  # recommended >= 15552000
# nextcloud_tls_cert: /path/to/cert
# nextcloud_tls_cert_key: /path/to/cert/key
# nextcloud_tls_cert_chain: /path/to/cert/chain
# cert_path: /path/where/cert/to/copy   # Default: /etc/ssl/
# nextcloud_tls_chain_file: /path/to/cert/chain/chain.pem
# nextcloud_tls_cert_file: /path/to/cert/cert.crt
# nextcloud_tls_cert_key_file: /path/to/cert/key/cert.key
# nextcloud_tls_src_chain: /path/to/cert/chain
# nextcloud_tls_src_cert: /path/to/cert
# nextcloud_tls_src_cert_key: /path/to/cert/key
nextcloud_tls_session_cache_size: 50m  # in Byte or human readable size notation (g/m/k)

# [APPS]
nextcloud_apps: {}
nextcloud_disable_apps: []
nextcloud_patch_user_saml_app: false  # Apply Workaround to lower-case REALM for REMOTE_USER environment-variable.

# [SYSTEM]
# nextcloud_mysql_root_pwd: "secret"
upgrade_packages_first: false
cert_path: "/etc/ssl/"
